### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by Maksims** [playcanvas/playcanvas-jsdoc-template#21]
Readme now does not contain any information.

Please add:
1. How to build (with local engine as well)
2. How to test with/without local server

**Comment by willeastcott** [comment]
Well, it's a bit lame, but normally when I'm updating this template, I just copy the files over what NPM installs to node_modules in the developer.playcanvas.com repo. There's almost certainly a much better way to do it but I'm not sure what...and I didn't want to document my hacky solution.

**Comment by Maksims** [comment]
Sorry, but I don't see in `package.json` any dependencies of developer.playcanvas.com or this repo of each other.

**Comment by willeastcott** [comment]
No, the API reference is built from the code in the `engine` repo, so the dependency is there:

https://github.com/playcanvas/engine/blob/master/package.json#L38

**Comment by Maksims** [comment]
So the way to compile docs, is to use `npm run docs` in https://github.com/playcanvas/engine repo, which will pull master of this repo, and generate docs into engine/docs/ folder. Which then can be viewed by either openning index.html, or serving engine/docs/ folder by webserver.

Currently there is no way to run docs generation from within this repo by either using local repo or remote (dependency)?

**Comment by willeastcott** [comment]
No, you should think of `developer.playcanvas.com` and the API reference as separate sites. `developer.playcanvas.com` (this repo) is the User Guide + Tutorials. `engine` repo is the API reference site. Jenkins merges them on deploy.
