### ISSUE TITLE
Analytics might not be collecting data

### ISSUE THREAD

**Issue by epreston** [playcanvas/playcanvas-jsdoc-template#54]
Google has stopped processing UA on July 1st and now requires GA4 analytics.

When I was reading through, I saw UA in a template.

Reference here: 
https://support.google.com/analytics/answer/13467533?hl=en#zippy=%2Cin-this-article

The template was:
https://github.com/playcanvas/playcanvas-jsdoc-template/blob/eb50e06352cf25d84d04626da51830c37aaaa7da/tmpl/analytics.hbs

The existing code looks like this and uses UA-XXX tag.

```js
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-23605814-1', 'auto');
  ga('send', 'pageview');
</script>
```

GA4 looks like this and uses a G-XXXXX tag.

```js
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag() { dataLayer.push(arguments); }
  gtag('js', new Date());

  gtag('config', 'G-XXXXXXXX');
</script>
```

**Comment by willeastcott** [comment]
Well spotted. I've just applied an update. 😄
